version: '3'

services:
  server:
    image: somewheregreeny/menuplanner-server:2.0.0
    container_name: appserver-blue

    build: ./menuplanner-chatbot-api
    ports:
      - "8080:8080"
    networks:
      - main_network

networks:
  main_network:
    external: true