version: '3'

services:
  server:
    image: somewheregreeny/menuplanner-server:2.0.0
    container_name: appserver

    build: ./server/menuplanner-chatbot-api
    ports:
      - "8080:8080"

  nginx:  
    image: somewheregreeny/nginx:1.0.0
    container_name: webserver

    build: ./server/nginx 
    ports: 
      - "80:80"